# 1. Creating Tensors in PyTorch

Tensors are like arrays in NumPy, but designed for deep learning!
They can store numbers and perform operations efficiently on GPUs.


In [1]:
import torch
import numpy as np


## 1. Creating Tensors from Lists

The simplest way: create a tensor from a Python list!


In [2]:
# Create a tensor from a list
t1 = torch.tensor([1, 2, 3, 4, 5])
print("1D tensor:")
print(t1)
print(f"Shape: {t1.shape}")
print(f"Size: {t1.size()}")
print()

# Create a 2D tensor (matrix)
t2 = torch.tensor([[1, 2, 3], 
                   [4, 5, 6]])
print("2D tensor (matrix):")
print(t2)
print(f"Shape: {t2.shape}")
print()

# Create a 3D tensor
t3 = torch.tensor([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("3D tensor:")
print(t3)
print(f"Shape: {t3.shape}")
print(f"Number of dimensions: {t3.dim()}")


1D tensor:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Size: torch.Size([5])

2D tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Number of dimensions: 3


## 2. Creating Tensors with Zeros and Ones

Create tensors filled with zeros or ones of a specific shape!


In [ ]:
# Create tensor filled with zeros
# Create 1D tensor with 5 columns by filling zeroes 
zeros_1d = torch.zeros(5)
print("1D tensor of zeros:")
print(zeros_1d)
print()

# Create 2D tensor with 3 rows, 4 columns by filling zeroes
zeros_2d = torch.zeros(3, 4)
print("2D tensor of zeros (3 rows, 4 columns):")
print(zeros_2d)
print()

# Create tensor filled with ones
# Similar to creating 1D, but this time, filling with ones
ones_1d = torch.ones(5)
print("1D tensor of ones:")
print(ones_1d)
print()

# Same as this, create 2D tensor, filling with ones
ones_2d = torch.ones(2, 3)
print("2D tensor of ones (2 rows, 3 columns):")
print(ones_2d)
print()

# Create tensor with specific value
# Create tensor with specific shape/dimension and filling with specific values
full_tensor = torch.full((2, 3), 5.0)
print("2D tensor filled with 5.0:")
print(full_tensor)


1D tensor of zeros:
tensor([0., 0., 0., 0., 0.])

2D tensor of zeros (3 rows, 4 columns):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

1D tensor of ones:
tensor([1., 1., 1., 1., 1.])

2D tensor of ones (2 rows, 3 columns):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

2D tensor filled with 5.0:
tensor([[5., 5., 5.],
        [5., 5., 5.]])


## 3. Creating Tensors from NumPy Arrays

Convert NumPy arrays to PyTorch tensors easily!


In [2]:
# Create NumPy array
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy array:")
print(np_array)
print(type(np_array))
print()

# Convert to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)
print("PyTorch tensor (from NumPy):")
print(torch_tensor)
print(type(torch_tensor))
print()

# Convert PyTorch tensor to NumPy
tensor_back = torch.tensor([1, 2, 3, 4, 5])
np_array_back = tensor_back.numpy()
print("Converted back to NumPy:")
print(np_array_back)
print(type(np_array_back))
print()

# Note: They share memory if using from_numpy()!
print("Note: torch.from_numpy() shares memory with NumPy array!")
print("Changes to one affect the other (unless you use .clone())")


NumPy array:
[1 2 3 4 5]
<class 'numpy.ndarray'>

PyTorch tensor (from NumPy):
tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>

Converted back to NumPy:
[1 2 3 4 5]
<class 'numpy.ndarray'>

Note: torch.from_numpy() shares memory with NumPy array!
Changes to one affect the other (unless you use .clone())


## 4. Creating Tensors with Random Values

Generate random tensors for initializing neural networks!


In [5]:
# Random values between 0 and 1
# Random values without specific range will automatically set within 0 to 1
# Remember: in Python, m <= range < n
# Therefore, m is inclusive within range
# But, n is not within range
random_tensor = torch.rand(3, 4) 
print("Random tensor (values between 0 and 1):")
print(random_tensor)
print()

# Random integers
# Create tensor object with random integer values
# within 0 (inclusive) untill 10 (not inclusive) - 9 will be the maximum random integer number
# Specify range of random integer, then, specify the dimension/shape of tensor
random_int = torch.randint(0, 10, (3, 4))
print("Random integers (0 to 9):")
print(random_int)
print()

# Random values from normal distribution (mean=0, std=1)
# Remember: mean = 0 the average of random number generated in tensor
#           std = 1 (standard deviation) the differences of average values generated in tensor
# Create random tensor object using normal distribution with specified shape/dimension
normal_tensor = torch.randn(3, 4)
print("Random values from normal distribution:")
print(normal_tensor)
print()

# Random values with specific range
# random_range = torch.rand(3, 4) * 10  # <-- Scale to 0-10 (10 will becomes as mean)
# To perform on creating random normal distribution tensor object with 
# specified mean and std by using:
# torch.randn(3, 4) * mean + std
random_range = torch.rand(3, 4) * 10 + 2
print("Random values scaled to 0-10:")
print("10 as mean, 2 as the standard deviation:")
print(random_range)


Random tensor (values between 0 and 1):
tensor([[0.4996, 0.2446, 0.1021, 0.4830],
        [0.8958, 0.5254, 0.7207, 0.6528],
        [0.6891, 0.5458, 0.3018, 0.9996]])

Random integers (0 to 9):
tensor([[4, 9, 1, 3],
        [6, 5, 6, 8],
        [2, 7, 5, 9]])

Random values from normal distribution:
tensor([[-1.0720, -0.0622, -0.7283,  0.1136],
        [-0.2807,  0.7983, -0.3177,  0.2922],
        [-0.9600, -0.8751,  0.0689, -0.6095]])

Random values scaled to 0-10:
10 as mean, 2 as the standard deviation:
tensor([[8.4632, 2.8926, 4.8631, 4.6529],
        [4.1229, 6.3192, 3.5082, 4.0427],
        [8.4917, 2.4006, 4.0293, 2.5276]])


## 5. Data Types (dtype)

Tensors can have different data types: float32, int64, etc.
Specify the type when creating tensors!


In [8]:
# Default float tensor
# By default, the data type will 'float32'
t_float = torch.tensor([1.0, 2.0, 3.0])
print("Float tensor (default - float32):")
print(t_float)
print(f"dtype: {t_float.dtype}")
print()

# Integer tensor
# Specifying tensor object datatype into 'int64'
t_int = torch.tensor([1, 2, 3], dtype=torch.int64)
print("Integer tensor:")
print(t_int)
print(f"dtype: {t_int.dtype}")
print()

# Float32 tensor (most common for neural networks)
t_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float32 tensor:")
print(t_float32)
print(f"dtype: {t_float32.dtype}")
print()

# Convert between types
# Creating tensor objects by specifying data types of float32 to int64
t_convert = torch.tensor([1, 2, 3], dtype=torch.int64)
t_float_converted = t_convert.float()
print("Original tensor (before conversion)")
print(t_convert)
print(f"dtype: {t_convert.dtype}")
print("Converted to float (notice the decimal point (.)):")
print(t_float_converted)
print(f"dtype: {t_float_converted.dtype}")
print()

# Common dtypes
print("Common dtypes:")
print(f"torch.float32 (or torch.float): 32-bit float")
print(f"torch.float64 (or torch.double): 64-bit float")
print(f"torch.int32 (or torch.int): 32-bit integer")
print(f"torch.int64 (or torch.long): 64-bit integer")


Float tensor (default - float32):
tensor([1., 2., 3.])
dtype: torch.float32

Integer tensor:
tensor([1, 2, 3])
dtype: torch.int64

Float32 tensor:
tensor([1., 2., 3.])
dtype: torch.float32

Original tensor (before conversion)
tensor([1, 2, 3])
dtype: torch.int64
Converted to float (notice the decimal point (.)):
tensor([1., 2., 3.])
dtype: torch.float32

Common dtypes:
torch.float32 (or torch.float): 32-bit float
torch.float64 (or torch.double): 64-bit float
torch.int32 (or torch.int): 32-bit integer
torch.int64 (or torch.long): 64-bit integer


## 6. Key Takeaways

**Creating tensors:**
- `torch.tensor([...])` - from list
- `torch.zeros(shape)` - filled with zeros
- `torch.ones(shape)` - filled with ones
- `torch.rand(shape)` - random values (0-1)
- `torch.randn(shape)` - random from normal distribution
- `torch.from_numpy(array)` - from NumPy array

**Important properties:**
- `tensor.shape` - dimensions of tensor
- `tensor.dtype` - data type (float32, int64, etc.)
- `tensor.dim()` - number of dimensions

**Remember:** Tensors are the building blocks of PyTorch!
