# 1. Single Neuron From Scratch

A neuron is the building block of neural networks!
It takes inputs, multiplies by weights, adds bias, and applies an activation function.
Let's build one from scratch!


In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt


## 1. What is a Neuron?

A neuron takes inputs, multiplies by weights, adds a bias, and applies an activation function!
Output = activation(weight1 × input1 + weight2 × input2 + ... + bias)


In [ ]:
# Manual calculation: single neuron
# Inputs
inputs = torch.tensor([2.0, 3.0])

# Weights - indicates the slope or tendency
weights = torch.tensor([0.5, 0.3])

# Bias - indicates the offset
bias = 0.1

# Compute weighted sum
weighted_sum = weights[0] * inputs[0] + weights[1] * inputs[1] + bias

print("Single Neuron Calculation:")
print(f"Inputs: {inputs}")
print(f"Weights: {weights}")
print(f"Bias: {bias}")
print()
# Weighted sum = (w_n x i_n) + b
print(f"Weighted sum = {weights[0]} × {inputs[0]} + {weights[1]} × {inputs[1]} + {bias}")
print(f"Weighted sum = {weighted_sum:.2f}")
print()

# Apply activation (sigmoid)
# Activation function used as the separation line
# to separate the classification between data points in vector space

# Activation function formula for sigmoid: 1/(1+e^(-weighted sum))
activation = 1 / (1 + torch.exp(-weighted_sum))
print(f"After activation (sigmoid): {activation:.4f}")
print()
print("This is how a single neuron works!")


Single Neuron Calculation:
Inputs: tensor([2., 3.])
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Weighted sum = 0.5 × 2.0 + 0.30000001192092896 × 3.0 + 0.1
Weighted sum = 2.00

After activation (sigmoid): 0.8808

This is how a single neuron works!


## 2. Step 1: Initialize a Neuron

First, let's create a neuron class that can store weights and bias.
We'll build it step by step!


In [ ]:
# Step 1: Create a simple neuron class that just stores weights and bias
class Neuron:
    """Single neuron from scratch - Step 1: Just initialization"""

        # during initalization, it has definition for weights and bias 
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        # REMEMBER: random number generated between 0 to 1
        # Generated number will be multiplied by 0.1 (but NOT ZERO - avoid vanishing gradient)
        #   to avoid oversaturation and overslope that the model
        #   does not have proper 'learning' to classify in identifying
        #   for activation function
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        #   to keep the NN neutral as possible at first
        #   while the weights will adjust and influence bias later on
        self.bias = torch.tensor(0.0)

# Let's create a neuron and see what it looks like
neuron = Neuron(num_inputs=2)

print("Step 1: Neuron Initialization")
print(f"Number of inputs: 2")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print("Good! Our neuron now has weights and bias initialized.")


Step 1: Neuron Initialization
Number of inputs: 2
Weights: tensor([0.0007, 0.1055])
Bias: 0.0

Good! Our neuron now has weights and bias initialized.


## 3. Step 2: Calculate Weighted Sum

Now let's add a method to calculate the weighted sum (weights · inputs + bias).


In [ ]:
# Step 2: Add method to calculate weighted sum
class Neuron:
    """Single neuron from scratch - Step 2: Add weighted sum calculation"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def weighted_sum(self, inputs):
        """Calculate: weights · inputs + bias"""
        # Added function to calculate weighted sum through dot product by using formula
        #   weighted_sum = (w_n x i_n) x b
        #       where:  w_n (weight at specific index)
        #               i_n (index at specific index)
        #               b (bias)
        return torch.dot(self.weights, inputs) + self.bias

# Test it
# Create neuron class
neuron = Neuron(num_inputs=2)
# Define fixed weights for demo
neuron.weights = torch.tensor([0.5, 0.3])  
# Define neuron's bias to 0.1
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])
# use calculation formula from class neuron specified
# 'self' argument automatically known from initialization
result = neuron.weighted_sum(inputs)

print("Step 2: Weighted Sum Calculation")
print(f"Inputs: {inputs}")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print(f"Weighted sum = weights · inputs + bias")
print(f"              = {neuron.weights} · {inputs} + {neuron.bias}")
print(f"              = ({neuron.weights[0]} x {inputs[0]}) + ({neuron.weights[1]} x {inputs[1]}) + {neuron.bias}")
print(f"              = {result:.4f}")
print()
print("Great! Now we can calculate the weighted sum.")


Step 2: Weighted Sum Calculation
Inputs: tensor([2., 3.])
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Weighted sum = weights · inputs + bias
              = tensor([0.5000, 0.3000]) · tensor([2., 3.]) + 0.1
              = (0.5 x 2.0) + (0.30000001192092896 x 3.0) + 0.1
              = 1.0 + 1.0 + 0.1
              = 2.0000

Great! Now we can calculate the weighted sum.


## 4. Step 3: Add Activation Function

The activation function makes the neuron non-linear. Let's add sigmoid activation first.


In [ ]:
# Step 3: Add sigmoid activation function
class Neuron:
    """Single neuron from scratch - Step 3: Add sigmoid activation"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def weighted_sum(self, inputs):
        """Calculate: weights · inputs + bias"""
        return torch.dot(self.weights, inputs) + self.bias
    
    # use sigmoid as the activation function
    # it converts the weighted_sum (function above) 
    #   from w_n*i_n + b (linear function)
    #   into non-linear function to classification between data points
    def sigmoid(self, x):
        """Sigmoid activation: 1 / (1 + exp(-x))"""
        # sigmoid formula: 1/(1+e^(-weighted_sum))
        return 1 / (1 + torch.exp(-x))

# Test it step by step
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])  # Set fixed weights for demo
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])

# Step 1: Calculate weighted sum
ws = neuron.weighted_sum(inputs)
print("Step 3: Adding Activation Function")
print(f"1. Weighted sum = {ws:.4f}")

# Step 2: Apply sigmoid
# Calculate using defined function using neuron class
output = neuron.sigmoid(ws)
print(f"2. After sigmoid activation = {output:.4f}")
print()
print("Perfect! Now we have a complete neuron with activation.")


Step 3: Adding Activation Function
1. Weighted sum = 2.0000
2. After sigmoid activation = 0.8808

Perfect! Now we have a complete neuron with activation.


## 5. Step 4: Complete Forward Pass

Now let's combine everything into a single `forward` method that does it all!

**What a neuron does:**
- Takes multiple inputs
- Multiplies by weights (importance of each input)
- Adds bias (shift the output)
- Applies activation function (non-linearity)

**Key components:**
- **Weights**: How important each input is
- **Bias**: Shifts the weighted sum
- **Activation**: Makes neuron non-linear (sigmoid, ReLU, tanh, etc.)

**Forward pass:**
1. Weighted sum = weights · inputs + bias
2. Output = activation(weighted sum)

**Remember:** A single neuron is the building block of neural networks!


In [20]:
# Step 4: Complete neuron with forward pass
class Neuron:
    """Single neuron from scratch - Complete version"""
    
    def __init__(self, num_inputs):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
    
    def sigmoid(self, x):
        """Sigmoid activation: 1 / (1 + exp(-x))"""
        return 1 / (1 + torch.exp(-x))

    def calculateWeightedSum(self, inputs):
        """"Calculate wrighted sum"""
        weighted_sum = torch.dot(self.weights, inputs) + self.bias
        return weighted_sum

    # forward consists of 
    #   - calculate weighted sum <-- integrate with function calculateWeightedSum
    #   - calculate activation function (sigmoid)
    def forward(self, inputs):
        """Forward pass: weighted sum + activation"""
        # Step 1: Calculate weighted sum
        weighted_sum = self.calculateWeightedSum(inputs)
        # Step 2: Apply activation
        output = self.sigmoid(weighted_sum)
        return output

# Test the complete neuron
neuron = Neuron(num_inputs=2)
neuron.weights = torch.tensor([0.5, 0.3])  # Set fixed weights for demo
neuron.bias = 0.1

inputs = torch.tensor([2.0, 3.0])
output = neuron.forward(inputs)

print("Step 4: Complete Forward Pass")
print(f"Inputs: {inputs}")
print()
print("Neuron:")
print(f"Weights: {neuron.weights}")
print(f"Bias: {neuron.bias}")
print()
print(f"Weighted Sum: {neuron.calculateWeightedSum(inputs)}")
print(f"Output (After calculating activation function sigmoid from weighted sum): {output:.4f}")
print()
print("Excellent! Our neuron is complete and working!")


Step 4: Complete Forward Pass
Inputs: tensor([2., 3.])

Neuron:
Weights: tensor([0.5000, 0.3000])
Bias: 0.1

Weighted Sum: 2.0
Output (After calculating activation function sigmoid from weighted sum): 0.8808

Excellent! Our neuron is complete and working!


## 6. Test with Different Inputs

Let's see how our neuron responds to different inputs!


In [21]:
# Test neuron with different inputs
# use the latest defined neuron class to create neuron object
neuron = Neuron(num_inputs=2)
# again, defining its weight for each inputs
neuron.weights = torch.tensor([0.5, 0.3])
# defining its bias
neuron.bias = 0.1

test_inputs = [
    torch.tensor([0.0, 0.0]),
    torch.tensor([1.0, 0.0]),
    torch.tensor([0.0, 1.0]),
    torch.tensor([1.0, 1.0]),
    torch.tensor([2.0, 3.0]),
]

print("Testing neuron with different inputs:")
print(f"Weights: {neuron.weights}, Bias: {neuron.bias}")
print()
print("Input          | Weighted Sum | Output (sigmoid)")
print("-" * 50)

for inp in test_inputs:
    weighted_sum = neuron.calculateWeightedSum(inp)
    output = neuron.forward(inp)
    print(f"{str(inp):14} | {weighted_sum:11.4f} | {output:14.4f}")


Testing neuron with different inputs:
Weights: tensor([0.5000, 0.3000]), Bias: 0.1

Input          | Weighted Sum | Output (sigmoid)
--------------------------------------------------
tensor([0., 0.]) |      0.1000 |         0.5250
tensor([1., 0.]) |      0.6000 |         0.6457
tensor([0., 1.]) |      0.4000 |         0.5987
tensor([1., 1.]) |      0.9000 |         0.7109
tensor([2., 3.]) |      2.0000 |         0.8808


## 8. Try Different Activation Functions

Neurons can use different activation functions! Let's add support for more activations.


In [ ]:
# Enhanced neuron with multiple activation functions
class Neuron:
    """Single neuron with multiple activation functions"""
    
    # initialization function by defininng 
    # activation = 'sigmoid' as default 
    def __init__(self, num_inputs, activation='sigmoid'):
        # Initialize weights randomly (small values)
        self.weights = torch.randn(num_inputs) * 0.1
        # Initialize bias to 0
        self.bias = torch.tensor(0.0)
        self.activation_name = activation
    
    # multiple activation function selection (sigmoid, relu, tanh)
    def activate(self, x):
        """Apply activation function"""
        if self.activation_name == 'sigmoid':
            return 1 / (1 + torch.exp(-x))
        elif self.activation_name == 'relu':
            return torch.maximum(torch.tensor(0.0), x)
        elif self.activation_name == 'tanh':
            return torch.tanh(x)
        else:
            # if input activation name not defined, do not set anything
            return x  # No activation (linear)
    
    def forward(self, inputs):
        """Forward pass: weighted sum + activation"""
        weighted_sum = torch.dot(self.weights, inputs) + self.bias
        output = self.activate(weighted_sum)
        return output

# Test different activation functions
print("Testing different activation functions:")
print("Input = 2.0, Weights = [1.0], Bias = 0.0")
print()

activations = ['sigmoid', 'relu', 'tanh', 'linear']

for act_name in activations:
    neuron = Neuron(num_inputs=1, activation=act_name)
    neuron.weights = torch.tensor([1.0])
    neuron.bias = 0.0
    
    input_val = torch.tensor([2.0])
    weighted_sum = torch.dot(neuron.weights, input_val) + neuron.bias
    output = neuron.forward(input_val)
    
    print(f"{act_name:8s}: weighted_sum = {weighted_sum:.2f} → output = {output:.4f}")


Testing different activation functions:
Input = 2.0, Weights = [1.0], Bias = 0.0

sigmoid : weighted_sum = 2.00 → output = 0.8808
relu    : weighted_sum = 2.00 → output = 2.0000
tanh    : weighted_sum = 2.00 → output = 0.9640
linear  : weighted_sum = 2.00 → output = 2.0000


## 10. Key Takeaways

**What a neuron does:**
- Takes multiple inputs
- Multiplies by weights (importance of each input)
- Adds bias (shift the output)
- Applies activation function (non-linearity)

**Key components:**
- **Weights**: How important each input is
- **Bias**: Shifts the weighted sum
- **Activation**: Makes neuron non-linear (sigmoid, ReLU, tanh, etc.)

**Forward pass:**
1. Weighted sum = weights · inputs + bias
2. Output = activation(weighted sum)

**Remember:** A single neuron is the building block of neural networks!
